export const mockJobs = [
  {
    id: 1,
    title: 'Frontend Developer',
    company: 'Northstar Labs',
    location: 'Makati City · Hybrid',
    type: 'Full-time',
    level: 'Junior',
    posted: 'Posted 2 days ago',
    initials: 'NL',
    color: 'coral',
    description: 'Build thoughtful, accessible interfaces with a collaborative product team.',
    skills: ['React', 'JavaScript', 'CSS'],
  },
  {
    id: 2,
    title: 'UI/UX Designer',
    company: 'Studio Sinta',
    location: 'Quezon City · Remote',
    type: 'Full-time',
    level: 'Associate',
    posted: 'Posted today',
    initials: 'SS',
    color: 'plum',
    description: 'Shape clear digital experiences from early concepts through polished delivery.',
    skills: ['Figma', 'Research', 'Prototyping'],
  },
  {
    id: 3,
    title: 'Marketing Coordinator',
    company: 'Common Ground Co.',
    location: 'Taguig City · On-site',
    type: 'Full-time',
    level: 'Entry level',
    posted: 'Posted 3 days ago',
    initials: 'CG',
    color: 'gold',
    description: 'Help plan campaigns and tell stories that connect brands with communities.',
    skills: ['Campaigns', 'Content', 'Analytics'],
  },
  {
    id: 4,
    title: 'Customer Success Associate',
    company: 'BrightDesk',
    location: 'Cebu City · Hybrid',
    type: 'Full-time',
    level: 'Entry level',
    posted: 'Posted 4 days ago',
    initials: 'BD',
    color: 'blue',
    description: 'Guide customers, solve practical problems, and make every interaction count.',
    skills: ['Support', 'Communication', 'CRM'],
  },
  {
    id: 5,
    title: 'Data Analyst Intern',
    company: 'Luntian Energy',
    location: 'Pasig City · Hybrid',
    type: 'Internship',
    level: 'Student',
    posted: 'Posted 5 days ago',
    initials: 'LE',
    color: 'green',
    description: 'Turn operational data into useful reports for a growing renewable energy team.',
    skills: ['Excel', 'SQL', 'Dashboards'],
  },
  {
    id: 6,
    title: 'People Operations Assistant',
    company: 'Harbor & Field',
    location: 'Manila · On-site',
    type: 'Full-time',
    level: 'Junior',
    posted: 'Posted 1 week ago',
    initials: 'HF',
    color: 'sand',
    description: 'Support a people-first workplace through reliable, caring day-to-day operations.',
    skills: ['HR Admin', 'Organization', 'People'],
  },
]
